# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://uat.mg.kmelearning.com/shyz/shyz/login")
    self.driver.set_window_size(1550, 838)
    self.driver.find_element(By.ID, "account").click()
    element = self.driver.find_element(By.ID, "account")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "account").send_keys("shyz")
    self.driver.find_element(By.CSS_SELECTOR, ".content__3Evaj").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Dfcv3344")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-menu-submenu-open > .ant-menu-submenu-title > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-menu-submenu-active > .ant-menu-submenu-title > span").click()
    self.driver.find_element(By.LINK_TEXT, "素材库").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-btn:nth-child(1)").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("素材名称")
    self.driver.find_element(By.CSS_SELECTOR, "#source .ant-select-selection__rendered").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-select-dropdown-menu-item-active").click()
    self.driver.find_element(By.CSS_SELECTOR, "#type .ant-select-selection__rendered").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-select-dropdown-menu-item-active").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-upload > .ant-btn").click()
  
